/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas1;

import Logica.Circunstancia;
import Logica.Controlador;
import Logica.Mascota;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author angel
 */
public class FrmDespertaryDormir extends javax.swing.JPanel {

    private int contador = 1;
    private Mascota mascota = Mascota.inicializar();

    /**
     * Creates new form FrmDespertaryDormir
     */
    public FrmDespertaryDormir() {
        initComponents();
//        BtnDormirse.setIcon(setIcono("/ImgDormirydespertar/BotonDormirse.jpg", BtnDormirse));
//        BtnDormirse.setPressedIcon(setIconoPresionado("/ImgDormirydespertar/BotonDormirse.jpg", BtnDormirse, 5, 5));
//        BtnDespertarse.setIcon(setIcono("/ImgDormirydespertar/Despertarse.jpg", BtnDespertarse));
//        BtnDespertarse.setPressedIcon(setIconoPresionado("/ImgDormirydespertar/Despertarse.jpg", BtnDespertarse, 5, 5));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnDormirse = new javax.swing.JButton();
        BtnDespertarse = new javax.swing.JButton();

        BtnDormirse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgDormirYdespertar/BotonDormirse.jpg"))); // NOI18N
        BtnDormirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDormirseActionPerformed(evt);
            }
        });

        BtnDespertarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgDormirYdespertar/Despertarse.jpg"))); // NOI18N
        BtnDespertarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDespertarseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(BtnDormirse, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(BtnDespertarse, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(240, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnDormirse, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(BtnDespertarse, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDespertarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDespertarseActionPerformed
        Controlador.getControlador().despertar();
        mascota.setCircunstancia(Circunstancia.Despierto);
        ciclo.stop();
        try {

            if (mascota.getEnergia() == 90 || mascota.getEnergia() == 100) {
                JOptionPane.showMessageDialog(null, " Que Rico es dormir");
                mascota.getCircunstancia();

            } else {
                JOptionPane.showMessageDialog(null, " Suaveee, Que tengo sueño");
                mascota.getCircunstancia();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No puedo Despertar por " + e.getMessage());
        }

    }//GEN-LAST:event_BtnDespertarseActionPerformed

    private void BtnDormirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDormirseActionPerformed
        Controlador.getControlador().dormir();
        mascota.setCircunstancia(Circunstancia.Dormido);
        ciclo.restart();
        try {
            if (mascota.getEnergia() >= 25) {
                JOptionPane.showMessageDialog(null, "ZZzzzZ Estoy Dormido");
            } else if (mascota.getEnergia() == 90) {
                JOptionPane.showMessageDialog(null, "Obligame a dormir ");
            } else {
                JOptionPane.showMessageDialog(null, "No Tengo Sueño");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Upps No puedor por");
        }
    }//GEN-LAST:event_BtnDormirseActionPerformed

    Timer ciclo = new Timer(1000, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            contador += 1;
            tiempoDormido();
        }
    });

    private void tiempoDormido() {
        if (contador == 10) {
            mascota.setEnergia(mascota.getEnergia() + 25);
            Controlador.getControlador().actualizar(mascota);
            contador = 1;
        }

    }

//    public Icon setIcono(String url, JButton boton) {
//
//        ImageIcon icon = new ImageIcon(getClass().getResource(url));
//
//        int ancho = boton.getWidth();
//        int alto = boton.getHeight();
//        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
//        return icono;
//    }
//
//    public Icon setIconoPresionado(String url, JButton boton, int ancho, int altura) {
//
//        ImageIcon icon = new ImageIcon(getClass().getResource(url));
//
//        int width = boton.getWidth() - ancho;
//        int height = boton.getHeight() - altura;
//
//        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
//
//        return icono;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDespertarse;
    private javax.swing.JButton BtnDormirse;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
