/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas1;

import Logica.Circunstancia;
import Logica.Controlador;
import Logica.Mascota;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author andre
 */
public class FRMLoby extends javax.swing.JFrame {

//    FrmAlimentos alimentos = new FrmAlimentos();
//    FrmEstado estados = new FrmEstado();
//    FrmMedicina medicinas = new FrmMedicina();
//    FrmActividades actividades = new FrmActividades();
//    FrmDespertaryDormir siesta = new FrmDespertaryDormir();
    Mascota mascota = Mascota.inicializar();
    private Controlador controlador;

    /**
     * Creates new form Juego
     */
    public FRMLoby() {
        initComponents();
        BtnBano.setIcon(setIcono("/ImgLoby/Icono baño.jpg", BtnBano));
        BtnBano.setPressedIcon(setIconoPresionado("/ImgLoby/Icono baño.jpg", BtnBano, 5, 5));
        BtnComida.setIcon(setIcono("/ImgLoby/icono Comidas.png", BtnComida));
        BtnComida.setPressedIcon(setIconoPresionado("/ImgLoby/icono Comidas.png", BtnComida, 5, 5));
        BtnDormir.setIcon(setIcono("/ImgLoby/BotonDormirse.jpg", BtnDormir));
        BtnDormir.setPressedIcon(setIconoPresionado("/ImgLoby/BotonDormirse.jpg", BtnDormir, 5, 5));
        BtnActividades.setIcon(setIcono("/ImgLoby/icono deportes.png", BtnActividades));
        BtnActividades.setPressedIcon(setIconoPresionado("/ImgLoby/icono deportes.png", BtnActividades, 5, 5));
        BtnMedicina.setIcon(setIcono("/ImgLoby/IconoHospital.jpg", BtnMedicina));
        BtnMedicina.setPressedIcon(setIconoPresionado("/ImgLoby/IconoHospital.jpg", BtnMedicina, 5, 5));
        //Nombrar();
        controlador = Controlador.inicializar(this, Mascota.inicializar());
        lblEdad.setText(Integer.toString(Mascota.inicializar().getEdad()));

//        PnlBotones.add(estados);
//        estados.setVisible(true);
//        alimentos.setVisible(false);
//        deshabilitar();
//        accionesBtns();
    }

    public int getEnergia() {
        return BarEnergia.getValue();
    }

    public void setEnergia(int val) {
        if (getEnergia() > 0 && getEnergia() <= 100) {
            this.BarEnergia.setValue(val);
        } else if (val < 0) {
            this.BarEnergia.setValue(0);
        } else if (val > 100) {
            this.BarEnergia.setValue(100);
        }
    }

    public int getSalud() {
        return BarSalud.getValue();
    }

    public void setSalud(int valor) {
        if (getSalud() >= 0) {
            this.BarSalud.setValue(valor);
        } else if (valor < 0) {
            this.BarSalud.setValue(0);
        } else if (valor > 100) {
            this.BarSalud.setValue(100);
        }
    }

    public int getAnimos() {
        return BarAnimo.getValue();
    }

    public void setAnimo(int val) {
        if (getAnimos() >= 0) {
            this.BarAnimo.setValue(val);
        } else if (val < 0) {
            this.BarAnimo.setValue(0);
        } else if (val > 100) {
            this.BarAnimo.setValue(100);
        }
    }

    public int getNecesidades() {
        return BarBano.getValue();
    }

    public void setNecesidades(int valor) {
        if (getNecesidades() >= 0) {
            this.BarBano.setValue(valor);
        } else if (valor < 0) {
            this.BarBano.setValue(0);
        } else if (valor > 100) {
            this.BarBano.setValue(100);
        }
    }

    public int getHambre() {
        return BarHambre.getValue();
    }

    public void setHambre(int valor) {
        if (getHambre() >= 0) {
            this.BarHambre.setValue(valor);
        } else if (valor < 0) {
            this.BarHambre.setValue(0);
        } else if (valor > 100) {
            this.BarHambre.setValue(100);
        }
    }

//    private void Nombrar() {
//        String nombre = JOptionPane.showInputDialog(null, "Ingrese el nombre de la mascota", "Bienvenido", 3);
//        this.lblNombre.setText(nombre);
//    }
//
    public void setlblEdad(String lblEdad) {
        this.lblEdad.setText(lblEdad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        ImageIcon icon = new ImageIcon(getClass().getResource("/ImgPrincipal/EscenarioLoby.jpg"));
        Image image = icon.getImage();
        dskLoby = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jPanel1 = new javax.swing.JPanel();
        BtnBano = new javax.swing.JButton();
        BtnActividades = new javax.swing.JButton();
        BtnComida = new javax.swing.JButton();
        BtnMedicina = new javax.swing.JButton();
        BtnDormir = new javax.swing.JButton();
        lblEtapa = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        Mostrar = new javax.swing.JPanel();
        BarEnergia = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        BarSalud = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        BarHambre = new javax.swing.JProgressBar();
        BarBano = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        BarAnimo = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jButton6.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setForeground(new java.awt.Color(255, 204, 102));

        BtnBano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBanoActionPerformed(evt);
            }
        });

        BtnActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActividadesActionPerformed(evt);
            }
        });

        BtnComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComidaActionPerformed(evt);
            }
        });

        BtnMedicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMedicinaActionPerformed(evt);
            }
        });

        BtnDormir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDormirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnComida, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMedicina, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBano, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDormir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnBano, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnDormir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnMedicina, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnComida, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblEtapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Pollo/Saludable/HuevoSaludable.jpg"))); // NOI18N

        lblEdad.setBackground(new java.awt.Color(255, 153, 0));
        lblEdad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lblNombre.setBackground(new java.awt.Color(255, 153, 0));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        Mostrar.setBackground(new java.awt.Color(255, 204, 102));

        javax.swing.GroupLayout MostrarLayout = new javax.swing.GroupLayout(Mostrar);
        Mostrar.setLayout(MostrarLayout);
        MostrarLayout.setHorizontalGroup(
            MostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        MostrarLayout.setVerticalGroup(
            MostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        BarEnergia.setValue(100);
        BarEnergia.setStringPainted(true);

        jLabel1.setText("Energia");

        BarSalud.setStringPainted(true);

        jLabel2.setText("Salud");

        BarHambre.setStringPainted(true);

        BarBano.setStringPainted(true);

        jLabel3.setText("Hambre");

        BarAnimo.setStringPainted(true);

        jLabel4.setText("Aburrimiento");

        jLabel5.setText("Ganas de ir");

        dskLoby.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLoby.setLayer(lblEtapa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLoby.setLayer(lblEdad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLoby.setLayer(lblNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLoby.setLayer(Mostrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLoby.setLayer(BarEnergia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLoby.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLoby.setLayer(BarSalud, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLoby.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLoby.setLayer(BarHambre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLoby.setLayer(BarBano, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLoby.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLoby.setLayer(BarAnimo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLoby.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLoby.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dskLobyLayout = new javax.swing.GroupLayout(dskLoby);
        dskLoby.setLayout(dskLobyLayout);
        dskLobyLayout.setHorizontalGroup(
            dskLobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dskLobyLayout.createSequentialGroup()
                .addGroup(dskLobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dskLobyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dskLobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(BarEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dskLobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BarSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dskLobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BarHambre, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dskLobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BarAnimo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dskLobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(BarBano, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dskLobyLayout.createSequentialGroup()
                        .addGroup(dskLobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dskLobyLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEtapa, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121))
                            .addGroup(dskLobyLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(Mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dskLobyLayout.setVerticalGroup(
            dskLobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dskLobyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dskLobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BarBano, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(BarEnergia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BarHambre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BarAnimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BarSalud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(dskLobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dskLobyLayout.createSequentialGroup()
                        .addGroup(dskLobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(dskLobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dskLobyLayout.createSequentialGroup()
                                .addGap(315, 315, 315)
                                .addGroup(dskLobyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dskLobyLayout.createSequentialGroup()
                                .addComponent(lblEtapa, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)))
                        .addComponent(Mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dskLoby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskLoby)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDormirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDormirActionPerformed
        try {
            InternoDespertaryDormir dormir = new InternoDespertaryDormir();
            Mostrar.add(dormir);
            dormir.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No puedo abrir la alacena por " + e.getMessage());
        }

    }//GEN-LAST:event_BtnDormirActionPerformed

    private void BtnMedicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMedicinaActionPerformed
        try {
            InternoMedicinas medicina = new InternoMedicinas();
            Mostrar.add(medicina);
            medicina.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No puedo abrir la alacena por " + e.getMessage());
        }

    }//GEN-LAST:event_BtnMedicinaActionPerformed

    private void BtnComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComidaActionPerformed
        try {
            IfrmAlimentos comida = new IfrmAlimentos();
            Mostrar.add(comida);
            comida.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No puedo abrir la alacena por " + e.getMessage());
        }

    }//GEN-LAST:event_BtnComidaActionPerformed

    private void BtnActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActividadesActionPerformed
        try {
            InternoActividades actividades = new InternoActividades();
            Mostrar.add(actividades);
            actividades.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No puedo abrir la alacena por " + e.getMessage());
        }
    }//GEN-LAST:event_BtnActividadesActionPerformed

    private void BtnBanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBanoActionPerformed
        if (mascota.getNecesidades() > 0 && Mascota.inicializar().getCircunstancia().equals(Circunstancia.Despierto)) {
            this.mascota.setNecesidades(mascota.getNecesidades());
            Controlador.getControlador().actualizar(mascota);
        } else {
            JOptionPane.showMessageDialog(null, "Tu Mascota ya no quiere ir al baño", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BtnBanoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMLoby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMLoby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMLoby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMLoby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMLoby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMLoby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMLoby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMLoby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMLoby().setVisible(true);
            }
        });
    }

    public Icon setIcono(String url, JButton boton) {

        ImageIcon icon = new ImageIcon(getClass().getResource(url));

        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }

    public Icon setIconoPresionado(String url, JButton boton, int ancho, int altura) {

        ImageIcon icon = new ImageIcon(getClass().getResource(url));

        int width = boton.getWidth() - ancho;
        int height = boton.getHeight() - altura;

        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));

        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarAnimo;
    private javax.swing.JProgressBar BarBano;
    private javax.swing.JProgressBar BarEnergia;
    private javax.swing.JProgressBar BarHambre;
    private javax.swing.JProgressBar BarSalud;
    private javax.swing.JButton BtnActividades;
    private javax.swing.JButton BtnBano;
    private javax.swing.JButton BtnComida;
    private javax.swing.JButton BtnDormir;
    private javax.swing.JButton BtnMedicina;
    private javax.swing.JPanel Mostrar;
    private javax.swing.JDesktopPane dskLoby;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEdad;
    public javax.swing.JLabel lblEtapa;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables

}
