/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas1;

import Logica.Circunstancia;
import Logica.Controlador;
import Logica.Mascota;
import Logica.Rutina;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class FrmMedicina extends javax.swing.JPanel {

    Rutina Medicacion = new Rutina();

    /**
     * Creates new form FrmMedicina
     */
    public FrmMedicina() {
        initComponents();
//        BtnInyeccion.setIcon(setIcono("/ImgMedicinas/Inyeccion.png", BtnInyeccion));
//
//        BtnInyeccion.setPressedIcon(setIconoPresionado("/ImgMedicinas/Inyeccion.png", BtnInyeccion, 5, 5));
//
//        BtnPastillas.setIcon(setIcono("/ImgMedicinas/Pastillas.png", BtnPastillas));
//
//        BtnPastillas.setPressedIcon(setIconoPresionado("/ImgMedicinas/Pastillas.png", BtnPastillas, 5, 5));
//
//        BtnPosionMagica.setIcon(setIcono("/ImgMedicinas/Posima.png", BtnPosionMagica));
//
//        BtnPosionMagica.setPressedIcon(setIconoPresionado("/ImgMedicinas/Posima.png", BtnPosionMagica, 5, 5));
    }

    private void aplicar(JButton btn, int val) {
        if (Mascota.inicializar().getCircunstancia().equals(Circunstancia.Despierto)) {
            Mascota.inicializar().curar(Medicacion.ConstMed(val));
            Controlador.getControlador().actualizar(Mascota.inicializar());
            Controlador.getControlador().bloqueo(btn, 10);
        } else {
            JOptionPane.showMessageDialog(null, "Tu Mascota no puede usar eso ahora", "Lo siento", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnInyeccion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BtnInyeccion1 = new javax.swing.JButton();
        BtnPastillas = new javax.swing.JButton();
        BtnPosionMagica = new javax.swing.JButton();

        BtnInyeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInyeccionActionPerformed(evt);
            }
        });

        BtnInyeccion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgMedicinas/Inyeccion.png"))); // NOI18N
        BtnInyeccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInyeccion1ActionPerformed(evt);
            }
        });

        BtnPastillas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgMedicinas/Pastillas.png"))); // NOI18N
        BtnPastillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPastillasActionPerformed(evt);
            }
        });

        BtnPosionMagica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgMedicinas/Posima.png"))); // NOI18N
        BtnPosionMagica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPosionMagicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnInyeccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(BtnPosionMagica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(BtnPastillas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnPosionMagica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPastillas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnInyeccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInyeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInyeccionActionPerformed
        aplicar(BtnInyeccion, 1);
    }//GEN-LAST:event_BtnInyeccionActionPerformed

    private void BtnInyeccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInyeccion1ActionPerformed
        aplicar(BtnInyeccion, 1);
    }//GEN-LAST:event_BtnInyeccion1ActionPerformed

    private void BtnPastillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPastillasActionPerformed
        aplicar(BtnPastillas, 2);
    }//GEN-LAST:event_BtnPastillasActionPerformed

    private void BtnPosionMagicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPosionMagicaActionPerformed
        aplicar(BtnPosionMagica, 3);
    }//GEN-LAST:event_BtnPosionMagicaActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMedicina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMedicina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMedicina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMedicina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMedicina().setVisible(true);
            }
        });
    }

//    public Icon setIcono(String url, JButton boton) {
//
//        ImageIcon icon = new ImageIcon(getClass().getResource(url));
//
//        int ancho = boton.getWidth();
//        int alto = boton.getHeight();
//        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
//        return icono;
//    }
//
//    public Icon setIconoPresionado(String url, JButton boton, int ancho, int altura) {
//
//        ImageIcon icon = new ImageIcon(getClass().getResource(url));
//        int width = boton.getWidth() - ancho;
//        int height = boton.getHeight() - altura;
//        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
//        return icono;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInyeccion;
    private javax.swing.JButton BtnInyeccion1;
    private javax.swing.JButton BtnPastillas;
    private javax.swing.JButton BtnPosionMagica;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
