/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Ventanas1;

import Logica.Circunstancia;
import Logica.Controlador;
import Logica.Mascota;
import Logica.Rutina;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class IfrmAlimentos extends javax.swing.JInternalFrame {

    Rutina Alimentacion = new Rutina();

    public IfrmAlimentos() {
        initComponents();

    }
// controlador alimentos
    private void Alimentar(JButton btn, int val) {
        if (Mascota.inicializar().getCondicion().equals(Circunstancia.Despierto) && Mascota.inicializar().getHambre() > 0) {
            Mascota.inicializar().comer(Alimentacion.ConstAlm(val));
            Controlador.getControlador().actualizar(Mascota.inicializar());
            Controlador.getControlador().bloqueo(btn, 10);
        } else {
            JOptionPane.showMessageDialog(null, "Tu Mascota no puede Comer ahora", "Lo siento", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnConcentrado = new javax.swing.JButton();
        BtnLombriz = new javax.swing.JButton();
        BtnAgua = new javax.swing.JButton();
        BtnLagartija = new javax.swing.JButton();
        BtnMaiz = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setTitle("Alimentos");

        BtnConcentrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgComida/Concentrado.jpg"))); // NOI18N
        BtnConcentrado.setText("jButton1");
        BtnConcentrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConcentradoActionPerformed(evt);
            }
        });

        BtnLombriz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgComida/Lombriz.jpg"))); // NOI18N
        BtnLombriz.setText("jButton1");
        BtnLombriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLombrizActionPerformed(evt);
            }
        });

        BtnAgua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgComida/Agua.png"))); // NOI18N
        BtnAgua.setText("jButton1");
        BtnAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAguaActionPerformed(evt);
            }
        });

        BtnLagartija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgComida/Lagartija.png"))); // NOI18N
        BtnLagartija.setText("jButton1");
        BtnLagartija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLagartijaActionPerformed(evt);
            }
        });

        BtnMaiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgComida/Maiz.jpg"))); // NOI18N
        BtnMaiz.setText("jButton1");
        BtnMaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMaizActionPerformed(evt);
            }
        });

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgPrincipal/close_25px.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnConcentrado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnMaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnLagartija, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnLombriz, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnConcentrado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnLagartija, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnLombriz, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAguaActionPerformed
        // TODO add your handling code here:
        Alimentar(BtnAgua, 1);

    }//GEN-LAST:event_BtnAguaActionPerformed

    private void BtnConcentradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConcentradoActionPerformed
        // TODO add your handling code here:
        Alimentar(BtnConcentrado, 2);
    }//GEN-LAST:event_BtnConcentradoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void BtnMaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMaizActionPerformed
        // TODO add your handling code here:
        Alimentar(BtnMaiz, 3);
    }//GEN-LAST:event_BtnMaizActionPerformed

    private void BtnLagartijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLagartijaActionPerformed
        // TODO add your handling code here:
        Alimentar(BtnLagartija, 5);
    }//GEN-LAST:event_BtnLagartijaActionPerformed

    private void BtnLombrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLombrizActionPerformed
        // TODO add your handling code here:
        Alimentar(BtnLombriz, 4);
    }//GEN-LAST:event_BtnLombrizActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgua;
    private javax.swing.JButton BtnConcentrado;
    private javax.swing.JButton BtnLagartija;
    private javax.swing.JButton BtnLombriz;
    private javax.swing.JButton BtnMaiz;
    private javax.swing.JButton btnCerrar;
    // End of variables declaration//GEN-END:variables
}
