/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Ventanas1;

import Logica.Circunstancia;
import Logica.Condicion;
import Logica.Controlador;
import Logica.Mascota;
import Logica.Rutina;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class InternoActividades extends javax.swing.JInternalFrame {

    Rutina Actividades = new Rutina();

    public InternoActividades() {
        initComponents();

    }
//Controlar acticvidad
    private void actividad(int val) {
        if (Mascota.inicializar().getCondicion().equals(Condicion.Saludable) && Mascota.inicializar().getCondicion().equals(Circunstancia.Despierto) && Mascota.inicializar().getAnimo() > 0) {
            Mascota.inicializar().entretenerse(Actividades.ConstActv(val));
            Controlador.getControlador().actualizar(Mascota.inicializar());

        } else {
            JOptionPane.showMessageDialog(null, "Tu Mascota No Puede Jugar Ahora", "Lo Siento", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCacarear = new javax.swing.JButton();
        BtnEscarbar = new javax.swing.JButton();
        BtnAleteaer = new javax.swing.JButton();
        BtnCorrer = new javax.swing.JButton();
        BtnVolar = new javax.swing.JButton();
        BtnCerrar = new javax.swing.JButton();

        setTitle("Actividades");

        BtnCacarear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgActividades/Cantando.jpg"))); // NOI18N
        BtnCacarear.setToolTipText("");
        BtnCacarear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCacarearActionPerformed(evt);
            }
        });

        BtnEscarbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgActividades/escarbar.jpg"))); // NOI18N
        BtnEscarbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEscarbarActionPerformed(evt);
            }
        });

        BtnAleteaer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgActividades/Aletear.jpg"))); // NOI18N
        BtnAleteaer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAleteaerActionPerformed(evt);
            }
        });

        BtnCorrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgActividades/caminar.jpg"))); // NOI18N
        BtnCorrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCorrerActionPerformed(evt);
            }
        });

        BtnVolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgActividades/Volando.jpg"))); // NOI18N
        BtnVolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolarActionPerformed(evt);
            }
        });

        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgPrincipal/close_25px.png"))); // NOI18N
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnVolar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnCorrer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAleteaer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnEscarbar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnCacarear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(BtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCorrer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVolar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAleteaer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEscarbar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCacarear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolarActionPerformed
        // TODO add your handling code here:
 actividad(5);
    }//GEN-LAST:event_BtnVolarActionPerformed

    private void BtnCorrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCorrerActionPerformed
        // TODO add your handling code here:
 actividad(4);
    }//GEN-LAST:event_BtnCorrerActionPerformed

    private void BtnAleteaerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAleteaerActionPerformed
        // TODO add your handling code here:
 actividad(1);
    }//GEN-LAST:event_BtnAleteaerActionPerformed

    private void BtnEscarbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEscarbarActionPerformed
        // TODO add your handling code here:
 actividad(3);
    }//GEN-LAST:event_BtnEscarbarActionPerformed

    private void BtnCacarearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCacarearActionPerformed
        // TODO add your handling code here:
        actividad(2);
    }//GEN-LAST:event_BtnCacarearActionPerformed

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAleteaer;
    private javax.swing.JButton BtnCacarear;
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton BtnCorrer;
    private javax.swing.JButton BtnEscarbar;
    private javax.swing.JButton BtnVolar;
    // End of variables declaration//GEN-END:variables
}
