/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Logica.Circunstancia;
import Logica.Condicion;
import Logica.Controlador;
import Logica.Mascota;
import Logica.Rutina;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class FrmActividades extends javax.swing.JPanel {

    Rutina Actividades = new Rutina();

    /**
     * Creates new form FrmActividades
     */
    public FrmActividades() {
        initComponents();
//        BtnAletear.setIcon(setIcono("/ImgActividades/Aletear.jpg", BtnAletear));
//        BtnAletear.setPressedIcon(setIconoPresionado("/ImgActividades/Aletear.jpg", BtnAletear, 5, 5));
//        BtnCacarear.setIcon(setIcono("/ImgActividades/Cantando.jpg", BtnCacarear));
//        BtnCacarear.setPressedIcon(setIconoPresionado("/ImgActividades/Cantando.jpg", BtnCacarear, 5, 5));
//        BtnVolar.setIcon(setIcono("/ImgActividades/caminar.jpg", BtnVolar));
//        BtnVolar.setPressedIcon(setIconoPresionado("/ImgActividades/caminar.jpg", BtnVolar, 5, 5));
//        BtnEscarbar.setIcon(setIcono("/ImgActividades/escarbar.jpg", BtnEscarbar));
//        BtnEscarbar.setPressedIcon(setIconoPresionado("/ImgActividades/escarbar.jpg", BtnEscarbar, 5, 5));
//        BtnCaminar.setIcon(setIcono("/ImgActividades/caminar.jpg", BtnCaminar));
//        BtnCaminar.setPressedIcon(setIconoPresionado("/ImgActividades/caminar.jpg", BtnCaminar, 5, 5));
    }

    private void actividad(int val) {
        if (Mascota.inicializar().getCondicion().equals(Condicion.Saludable) && Mascota.inicializar().getCondicion().equals(Circunstancia.Despierto) && Mascota.inicializar().getAnimo() > 0) {
            Mascota.inicializar().entretenerse(Actividades.ConstActv(val));
            Controlador.getControlador().actualizar(Mascota.inicializar());

        } else {
            JOptionPane.showMessageDialog(null, "Tu Mascota No Puede Jugar Ahora", "Lo Siento", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnCacarear = new javax.swing.JButton();
        BtnAletear = new javax.swing.JButton();
        BtnVolar = new javax.swing.JButton();
        BtnEscarbar = new javax.swing.JButton();
        BtnCaminar = new javax.swing.JButton();

        BtnCacarear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgActividades/Cantando.jpg"))); // NOI18N
        BtnCacarear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCacarearActionPerformed(evt);
            }
        });

        BtnAletear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgActividades/Aletear.jpg"))); // NOI18N
        BtnAletear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAletearActionPerformed(evt);
            }
        });

        BtnVolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgActividades/Volando.jpg"))); // NOI18N
        BtnVolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolarActionPerformed(evt);
            }
        });

        BtnEscarbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgActividades/escarbar.jpg"))); // NOI18N
        BtnEscarbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEscarbarActionPerformed(evt);
            }
        });

        BtnCaminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgActividades/caminar.jpg"))); // NOI18N
        BtnCaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCaminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BtnAletear, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCacarear, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnEscarbar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnVolar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCacarear, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVolar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEscarbar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAletear, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCacarearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCacarearActionPerformed
        actividad(2);
    }//GEN-LAST:event_BtnCacarearActionPerformed

    private void BtnAletearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAletearActionPerformed
        actividad(1);
    }//GEN-LAST:event_BtnAletearActionPerformed

    private void BtnVolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolarActionPerformed
        actividad(5);
    }//GEN-LAST:event_BtnVolarActionPerformed

    private void BtnEscarbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEscarbarActionPerformed
        actividad(3);
    }//GEN-LAST:event_BtnEscarbarActionPerformed

    private void BtnCaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCaminarActionPerformed
        actividad(4);
    }//GEN-LAST:event_BtnCaminarActionPerformed
//    public Icon setIcono(String url, JButton boton) {
//
//        ImageIcon icon = new ImageIcon(getClass().getResource(url));
//
//        int ancho = boton.getWidth();
//        int alto = boton.getHeight();
//        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
//        return icono;
//    }
//
//    public Icon setIconoPresionado(String url, JButton boton, int ancho, int altura) {
//
//        ImageIcon icon = new ImageIcon(getClass().getResource(url));
//
//        int width = boton.getWidth() - ancho;
//        int height = boton.getHeight() - altura;
//
//        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(width, height, Image.SCALE_DEFAULT));
//
//        return icono;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAletear;
    private javax.swing.JButton BtnCacarear;
    private javax.swing.JButton BtnCaminar;
    private javax.swing.JButton BtnEscarbar;
    private javax.swing.JButton BtnVolar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
